# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160607_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='code',
        ),
    ]
