# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_myuser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='adjective_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='adjective_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='adjective_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='adjective_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='adjective_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='adjective_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='adjective_9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_18',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='interest_9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='metric_11',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='metric_12',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='metric_13',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='metric_14',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='metric_15',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='metric_16',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='metric_17',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='metric_18',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='response',
            name='value_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='value_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='value_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='value_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='value_9',
            field=models.IntegerField(default=0),
        ),
    ]
