# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20160707_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='email_1',
        ),
       
        ),
        migrations.RemoveField(
            model_name='response',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='response',
            name='email_3',
        ),
        migrations.RemoveField(
            model_name='response',
            name='email_4',
        ),
        migrations.RemoveField(
            model_name='response',
            name='email_5',
        ),
        migrations.RemoveField(
            model_name='response',
            name='email_6',
        ),
        
        
        migrations.AddField(
            model_name='myuser',
            name='email_1',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
       
        migrations.AddField(
            model_name='myuser',
            name='email_2',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='email_3',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='email_4',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='email_5',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='email_6',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        
       
        
    ]
