# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20160709_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_score', models.IntegerField()),
                ('PC_score', models.IntegerField()),
                ('PE_score', models.IntegerField()),
                ('PN_score', models.IntegerField()),
                ('PA_score', models.IntegerField()),
                ('II_score', models.IntegerField()),
                ('IA_score', models.IntegerField()),
                ('IC_score', models.IntegerField()),
                ('IS_score', models.IntegerField()),
                ('IR_score', models.IntegerField()),
                ('IE_score', models.IntegerField()),
                ('VPS_score', models.IntegerField()),
                ('VFR_score', models.IntegerField()),
                ('VFF_score', models.IntegerField()),
                ('VL_score', models.IntegerField()),
                ('VBC_score', models.IntegerField()),
                ('VA_score', models.IntegerField()),
                ('VR_score', models.IntegerField()),
                ('VJS_score', models.IntegerField()),
                ('VRT_score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
