# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_userscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50)),
                ('PO_score', models.IntegerField()),
                ('PC_score', models.IntegerField()),
                ('PE_score', models.IntegerField()),
                ('PN_score', models.IntegerField()),
                ('PA_score', models.IntegerField()),
                ('II_score', models.IntegerField()),
                ('IA_score', models.IntegerField()),
                ('IC_score', models.IntegerField()),
                ('IS_score', models.IntegerField()),
                ('IR_score', models.IntegerField()),
                ('IE_score', models.IntegerField()),
                ('VPS_score', models.IntegerField()),
                ('VFR_score', models.IntegerField()),
                ('VFF_score', models.IntegerField()),
                ('VL_score', models.IntegerField()),
                ('VBC_score', models.IntegerField()),
                ('VA_score', models.IntegerField()),
                ('VR_score', models.IntegerField()),
                ('VJS_score', models.IntegerField()),
                ('VRT_score', models.IntegerField()),
            ],
        ),
    ]
