# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20160730_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50)),
                ('po_weight', models.IntegerField()),
                ('pc_weight', models.IntegerField()),
                ('pe_weight', models.IntegerField()),
                ('pn_weight', models.IntegerField()),
                ('pa_weight', models.IntegerField()),
                ('ii_weight', models.IntegerField()),
                ('ia_weight', models.IntegerField()),
                ('ic_weight', models.IntegerField()),
                ('is_weight', models.IntegerField()),
                ('ir_weight', models.IntegerField()),
                ('ie_weight', models.IntegerField()),
                ('vlp_weight', models.IntegerField()),
                ('vps_weight', models.IntegerField()),
                ('vfr_weight', models.IntegerField()),
                ('vff_weight', models.IntegerField()),
                ('vl_weight', models.IntegerField()),
                ('vbc_weight', models.IntegerField()),
                ('va_weight', models.IntegerField()),
                ('vr_weight', models.IntegerField()),
                ('vjs_weight', models.IntegerField()),
                ('vrt_weight', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='alumniscores',
            options={'ordering': ['major']},
        ),
    ]
