# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20160802_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMajors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_1', models.CharField(blank=True, default='', max_length=30)),
                ('major_2', models.CharField(blank=True, default='', max_length=30)),
                ('major_3', models.CharField(blank=True, default='', max_length=30)),
                ('major_4', models.CharField(blank=True, default='', max_length=30)),
                ('major_5', models.CharField(blank=True, default='', max_length=30)),
                ('major_6', models.CharField(blank=True, default='', max_length=30)),
                ('major_7', models.CharField(blank=True, default='', max_length=30)),
                ('major_8', models.CharField(blank=True, default='', max_length=30)),
                ('major_9', models.CharField(blank=True, default='', max_length=30)),
                ('major_10', models.CharField(blank=True, default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='majorscores',
            options={'ordering': ['major']},
        ),
    ]
