# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20160823_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermajors',
            name='major_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_10',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_6',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_7',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_8',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usermajors',
            name='major_9',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
