# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20160823_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='major_1',
        ),
        migrations.RemoveField(
            model_name='response',
            name='major_2',
        ),
        migrations.RemoveField(
            model_name='response',
            name='major_3',
        ),
        migrations.RemoveField(
            model_name='response',
            name='major_4',
        ),
        migrations.RemoveField(
            model_name='response',
            name='major_5',
        ),
        migrations.RemoveField(
            model_name='usermajors',
            name='major_10',
        ),
        migrations.RemoveField(
            model_name='usermajors',
            name='major_9',
        ),
    ]
